name: skinsafe_analyzer
description: "An app to analyze skincare and cosmetic products for harmful ingredients"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  
  # ML and OCR
  google_ml_kit: ^0.20.0
  camera: ^0.10.6
  image_picker: ^1.1.2
  
  # UI components
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  
  # State management
  provider: ^6.1.4
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  http: ^1.3.0
  dio: ^5.8.0+1
  path: ^1.9.1
  share_plus: ^10.1.4
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1
  logger: ^2.5.0
  
  # Storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  google_mlkit_smart_reply: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/fonts/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
